#! /bin/sh

#AutoStart
pgrep -x sxhkd > /dev/null || sxhkd &
# xrandr --output HDMI-0 --primary --rotate normal --rate 144 --output DP-4 --rotate normal --right-of DP-4 &
picom --experimental-backends &
feh --bg-fill --randomize ~/Pictures/wallpapers/retrovader.jpg #wallpaper

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#bb2d7a"

bspc config border_width        1
bspc config window_gap          12
bspc config split_ratio         0.60

$HOME/.config/polybar/launch.sh
